version: '3.9'
services:
  mysqldb:
    image: mysql:8.0.21
    platform: linux/x86_64 
    container_name: mysqldb
    ports: #rede local : rede interna dos containeres
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
